# Generated by Django 3.0.7 on 2021-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='save',
            name='image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
