# Generated by Django 3.0.7 on 2021-06-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence2', '0002_auto_20210531_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
