# Generated by Django 3.0.7 on 2021-03-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='venkat1',
            new_name='intelligence3',
        ),
    ]
